default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        exclude: alembic/
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
        exclude: alembic/
    -   id: trailing-whitespace
        exclude: alembic/
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: alembic/
