default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        exclude: alembic/
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
        exclude: alembic/
    -   id: trailing-whitespace
        exclude: alembic/
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        exclude: alembic/
