"""empty message

Revision ID: 28a542cd2fe0
Revises: 360654b5a383
Create Date: 2024-01-24 14:20:13.981236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a542cd2fe0'
down_revision = '360654b5a383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
