"""empty message

Revision ID: ad31a9dcc0ec
Revises: eb6bf976c13c
Create Date: 2024-01-21 16:22:19.706053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad31a9dcc0ec'
down_revision = 'eb6bf976c13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
