# .github/workflows/**main.yml**
name: 7-command-backend workflow

on:
  push:
    branches:
      - main  # измените на вашу ветку по умолчанию

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
      - name: Login to Docker
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}git
        with:
          context: .  # путь к проекту FastAPI
          file: ./Dockerfile  # путь к вашему Dockerfile
          push: true
          tags: image-7-c:latest  # имя образа
          build-args: |
            BASE_IMAGE=python:3.10-slim
